remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Architect will respect the following variables, if set in your site's _config.yml:
# title: [The title of your site]
# description: [A short description of your site's purpose]

# Additionally, you may choose to set the following optional variables:
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
